version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s [%(filename)s:%(lineno)d]"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers: {}

loggers:
  root:
    level: WARNING

  moss:
    level: INFO
